### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by sarendipitee** [ractivejs/ractive-events-hover#4]
Would you mind doing a quick `npm publish` of the latest on this? The [version](https://www.npmjs.com/package/ractive-events-hover) on NPM is v0.1.0 and it actually has an issue with a capital "R" in the UMD loader for `require("Ractive")` that fucks up builds in case-sensitive file systems. The source version, not on npm, has a lowercase "r".

**Comment by JonDum** [comment]
Bump....

**Comment by rstacruz** [comment]
@rich-harris? :-)

in the mean time, you can use `npm install ractivejs/ractive-events-hover`.

**Comment by Rich-Harris** [comment]
Sorry! Been swamped. Have updated the plugin so that it no longer self-registers if you're using a module system (i.e. like the others), so you have to do this sort of thing:

```js
import hover from 'ractive-events-hover';

r = new Ractive({
  ...,
  events: { hover }
});
```

**Comment by JonDum** [comment]
ractive-events-hover on npm still not updated :|

**Comment by JonDum** [comment]
@rstacruz The `main` in package.json doesn't point to anything, so it's not very useful to check out the repo. Only way to use this code is to copy/paste into your own project, ignoring npm.

**Comment by rstacruz** [comment]
ack! that's embarassing—i've fixed the `main` field, try it now.

**Comment by Madgvox** [comment]
the package.json from npm is still pointing to `"ractive-events-hover.js"` instead of `"dist/ractive-events-hover.js"`: https://tonicdev.com/npm/ractive-events-hover
